export const PageObjOne = {
  img: require("../../images/svg-4.svg").default,
  header: "Reduce Expenses",
  text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elit sed vulputate mi sit amet mauris commodo. Dignissim sodales ut eu sem integer vitae justo. Ut tristique et egestas quis ipsum suspendisse. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Leo a diam sollicitudin tempor id. Cursus euismod quis viverra nibh. Sit amet aliquam id diam maecenas ultricies. Urna et pharetra pharetra massa massa ultricies. Ornare suspendisse sed nisi lacus sed. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. In aliquam sem fringilla ut. Facilisi cras fermentum odio eu feugiat pretium. Vel orci porta non pulvinar neque laoreet suspendisse. Habitant morbi tristique senectus et. Bibendum enim facilisis gravida neque convallis a cras. Iaculis at erat pellentesque adipiscing commodo elit at. Odio aenean sed adipiscing diam donec adipiscing. Pellentesque sit amet porttitor eget dolor morbi non arcu. Diam sit amet nisl suscipit adipiscing bibendum.",
};

export const PageObjTwo = {
  img: require("../../images/svg-5.svg").default,
  header: "Virtual Offices",
  text: "Sit amet volutpat consequat mauris nunc congue. Tempus quam pellentesque nec nam aliquam sem et. Eget nunc lobortis mattis aliquam faucibus purus in. Elementum nibh tellus molestie nunc non blandit massa. Vulputate eu scelerisque felis imperdiet proin fermentum. Sem nulla pharetra diam sit amet nisl. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. Ac orci phasellus egestas tellus rutrum tellus. Eu turpis egestas pretium aenean pharetra magna. Elementum nibh tellus molestie nunc non blandit massa enim. Elit scelerisque mauris pellentesque pulvinar pellentesque. Proin fermentum leo vel orci porta non pulvinar neque laoreet. Eget arcu dictum varius duis at consectetur lorem donec. Ultrices sagittis orci a scelerisque purus semper eget duis at. Nibh tellus molestie nunc non blandit massa enim nec dui. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Blandit turpis cursus in hac habitasse.",
};

export const PageObjThree = {
  img: require("../../images/svg-6.svg").default,
  header: "Perimuim Benefits",
  text: "Vitae et leo duis ut diam quam nulla porttitor massa. Sit amet porttitor eget dolor morbi. Nisl suscipit adipiscing bibendum est ultricies integer. Libero nunc consequat interdum varius sit amet. In egestas erat imperdiet sed. Elit pellentesque habitant morbi tristique senectus et netus et malesuada. Morbi tristique senectus et netus et malesuada fames ac turpis. Est ultricies integer quis auctor elit. Amet est placerat in egestas erat. Consequat interdum varius sit amet mattis vulputate enim nulla. Velit scelerisque in dictum non consectetur a erat nam. Odio eu feugiat pretium nibh ipsum consequat nisl. Ac tortor dignissim convallis aenean et tortor at. Lobortis mattis aliquam faucibus purus in massa tempor nec. Aenean et tortor at risus viverra adipiscing at in tellus. Nulla facilisi morbi tempus iaculis urna id volutpat.Volutpat commodo sed egestas egestas. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. A condimentum vitae sapien pellentesque habitant morbi. Nunc faucibus a pellentesque sit amet porttitor eget. Tristique et egestas quis ipsum. Ac turpis egestas maecenas pharetra convallis posuere morbi leo. Lorem sed risus ultricies tristique nulla aliquet enim. Volutpat odio facilisis mauris sit. Duis tristique sollicitudin nibh sit. Pellentesque nec nam aliquam sem. Cras pulvinar mattis nunc sed blandit libero. Tellus mauris a diam maecenas sed enim ut.",
};
